In [1]:
##Ques:-1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.
#Ans:-Let's Create a 3x3 NumPy array with random integers between 1 and 100, and then interchange its rows and columns:-

import numpy as np

# Create a 3x3 array with random integers between 1 and 100
random_array = np.random.randint(low=1, high=101, size=(3, 3))

print("Original array:")
print(random_array)

# Interchange rows and columns (transpose the array)
interchanged_array = random_array.T

print("\nInterchanged array (rows and columns swapped):")
print(interchanged_array)


Original array:
[[23 94 65]
 [99 86 75]
 [14 28 55]]

Interchanged array (rows and columns swapped):
[[23 99 14]
 [94 86 28]
 [65 75 55]]


In [2]:
##2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.
#Ans:- Let’s create that NumPy array and perform the reshaping steps:

#Generate a 1D NumPy array with 10 elements:

import numpy as np

# Create a 1D array with 10 elements
array = np.arange(10)

#Reshape into a 2x5 array:
reshaped_2x5 = array.reshape(2, 5)

#Reshape into a 5x2 array:
reshaped_5x2 = array.reshape(5, 2)

print("1D array:")
print(array)
print("\n2x5 array:")
print(reshaped_2x5)
print("\n5x2 array:")
print(reshaped_5x2)

1D array:
[0 1 2 3 4 5 6 7 8 9]

2x5 array:
[[0 1 2 3 4]
 [5 6 7 8 9]]

5x2 array:
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [3]:
##Ques:-3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.
#Ans:-Let's Create a 4x4 NumPy array with random float values and then add a border of zeros around it to make it a 6x6 array:-

import numpy as np

# Create a 4x4 array with random float values between 0 and 1
array = np.random.rand(4, 4)

print("Original 4x4 array:")
print(array)

# Add a border of zeros to create a 6x6 array
bordered_array = np.pad(array, pad_width=1, mode='constant')

print("\n6x6 array with zeros border:")
print(bordered_array)

Original 4x4 array:
[[0.22481333 0.20219705 0.0251414  0.7986357 ]
 [0.64118329 0.51454286 0.24453364 0.62710732]
 [0.93553373 0.28294576 0.01383507 0.62596739]
 [0.50861795 0.78121749 0.20533734 0.26891731]]

6x6 array with zeros border:
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.22481333 0.20219705 0.0251414  0.7986357  0.        ]
 [0.         0.64118329 0.51454286 0.24453364 0.62710732 0.        ]
 [0.         0.93553373 0.28294576 0.01383507 0.62596739 0.        ]
 [0.         0.50861795 0.78121749 0.20533734 0.26891731 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


In [4]:
##Ques:-4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.
#Ans:-Let's Create an array of integers from 10 to 60 with a step of 5:-

import numpy as np

# Create the array
my_array = np.arange(10, 61, 5)

print("Generated array:")
print(my_array)

Generated array:
[10 15 20 25 30 35 40 45 50 55 60]


In [10]:
##Ques:- 5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.
#Ans:-Let's Create a NumPy array of strings ['python', 'numpy', 'pandas'] and apply various case transformations to each element:-

import numpy as np

# Create the array
string_array = np.array(['python', 'numpy', 'pandas'])

# Uppercase
uppercase_array = np.char.upper(string_array)

# Lowercase
lowercase_array = np.char.lower(string_array)

# Title case
titlecase_array = np.char.title(string_array)

print("Original array:", string_array)
print("Uppercase array:", uppercase_array)
print("Lowercase array:", lowercase_array)
print("Title case array:", titlecase_array)

Original array: ['python' 'numpy' 'pandas']
Uppercase array: ['PYTHON' 'NUMPY' 'PANDAS']
Lowercase array: ['python' 'numpy' 'pandas']
Title case array: ['Python' 'Numpy' 'Pandas']


In [9]:
##Ques:- 6. Generate a NumPy array of words. Insert a space between each character of every word in the array.
#Ans:- Let's Generate a NumPy array of words and insert a space between each character of every word in the array:

import numpy as np

# Create a NumPy array of words
words = np.array(["hello", "world", "numpy", "array"])

# Insert a space between each character of every word
spaced_words = np.char.join(" ", words)

print("Original array:")
print(words)
print("\nWords with spaces between characters:")
print(spaced_words)

Original array:
['hello' 'world' 'numpy' 'array']

Words with spaces between characters:
['h e l l o' 'w o r l d' 'n u m p y' 'a r r a y']


In [8]:
##Ques:- 7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.
#Ans:-Example of using NumPy to create two 2D arrays and perform element-wise arithmetic operations:-

import numpy as np

# Create two 2D arrays
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])

# Element-wise addition
addition = array1 + array2

# Element-wise subtraction
subtraction = array1 - array2

# Element-wise multiplication
multiplication = array1 * array2

# Element-wise division
division = array1 / array2

print("Array 1:\n", array1)
print("Array 2:\n", array2)
print("Addition:\n", addition)
print("Subtraction:\n", subtraction)
print("Multiplication:\n", multiplication)
print("Division:\n", division)


Array 1:
 [[1 2 3]
 [4 5 6]]
Array 2:
 [[ 7  8  9]
 [10 11 12]]
Addition:
 [[ 8 10 12]
 [14 16 18]]
Subtraction:
 [[-6 -6 -6]
 [-6 -6 -6]]
Multiplication:
 [[ 7 16 27]
 [40 55 72]]
Division:
 [[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


In [7]:
##Ques:- 8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.
#Ans:-Let's Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.identity(5)

# Extract the diagonal elements
diagonal_elements = np.diag(identity_matrix)

print("Identity Matrix:")
print(identity_matrix)
print("\nDiagonal Elements:")
print(diagonal_elements)


Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagonal Elements:
[1. 1. 1. 1. 1.]


In [6]:
##Ques:-9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.
#Ans:-Let's Generates a NumPy array of 100 random integers between 0 and 1000, and then finds and displays all the prime numbers in this array:-
import numpy as np

# Function to check if a number is prime
def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(np.sqrt(n)) + 1):
        if n % i == 0:
            return False
    return True

# Generate a NumPy array of 100 random integers between 0 and 1000
random_array = np.random.randint(0, 1000, 100)

# Find all prime numbers in the array
prime_numbers = [num for num in random_array if is_prime(num)]

print("Random Array:", random_array)
print("Prime Numbers:", prime_numbers)

Random Array: [411 190  84 110 521 263  40 214 505 265 883 366 547 388 707 867 222  41
 425 326 977 107 520 987 702  64 422   3 480 544 139 231 533 933  14 942
 242 150 769  76 340 375 888 189 910 108 279 112 449 576 751 369 473 143
 951 460 508 874 915 747 131 134 762 977 357 212 197 877 592 393 294 653
 874 930 409 989 148 113 930  25 403 298 590 568 844  54 453 703 163 356
 865 941 339 185 843 562 902 854 267 978]
Prime Numbers: [521, 263, 883, 547, 41, 977, 107, 3, 139, 769, 449, 751, 131, 977, 197, 877, 653, 409, 113, 163, 941]


In [5]:
##Ques:- 10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.
#Ans:-Let's Create a NumPy array representing daily temperatures for a month and then calculate the weekly averages.

#Create a NumPy array for daily temperatures: We’ll assume the temperatures are in degrees Celsius and randomly generate them for simplicity.
#Calculate the weekly averages: We’ll divide the month into weeks and compute the average temperature for each week.

import numpy as np

# Generate random daily temperatures for a month (30 days)
daily_temperatures = np.random.randint(20, 40, size=30)

# Calculate weekly averages
weekly_averages = [np.mean(daily_temperatures[i:i+7]) for i in range(0, len(daily_temperatures), 7)]

# Display the results
print("Daily Temperatures:", daily_temperatures)
print("Weekly Averages:", weekly_averages)

Daily Temperatures: [25 38 28 36 32 32 21 27 35 28 24 20 38 21 23 34 25 29 31 21 22 31 37 20
 34 34 22 20 36 34]
Weekly Averages: [30.285714285714285, 27.571428571428573, 26.428571428571427, 28.285714285714285, 35.0]
